plugins:
  brightcove_enabled:
    default: false
    client: true
  brightcove_account_id:
    default: ""
    client: true
  brightcove_client_id:
    default: ""
  brightcove_client_secret:
    default: ""
    secret: true
  brightcove_application_id:
    default: "Discourse"
    client: true
  brightcove_folder_id:
    default: ""
  brightcove_player:
    default: "default"
    client: true
  brightcove_embed:
    default: "default"
    client: true
  brightcove_min_trust_level:
    default: 1
    enum: 'TrustLevelSetting'
    client: true
  brightcove_file_extensions:
    default: "mp4|mov|wmv"
    type: 'list'
    client: true
  brightcove_uploads_per_day_per_user:
    default: 10